// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http",
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "title": "proto/helloword.proto",
    "version": "version not set"
  },
  "paths": {
    "/v1/example/echo": {
      "post": {
        "tags": [
          "Greeter"
        ],
        "summary": "Sends a greeting",
        "operationId": "SayHello",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/protoHelloRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "$ref": "#/definitions/protoHelloReply"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "protoHelloReply": {
      "type": "object",
      "title": "The response message containing the greetings",
      "properties": {
        "message": {
          "type": "string"
        }
      }
    },
    "protoHelloRequest": {
      "description": "The request message containing the user's name.",
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http",
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "title": "proto/helloword.proto",
    "version": "version not set"
  },
  "paths": {
    "/v1/example/echo": {
      "post": {
        "tags": [
          "Greeter"
        ],
        "summary": "Sends a greeting",
        "operationId": "SayHello",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/protoHelloRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "$ref": "#/definitions/protoHelloReply"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "protoHelloReply": {
      "type": "object",
      "title": "The response message containing the greetings",
      "properties": {
        "message": {
          "type": "string"
        }
      }
    },
    "protoHelloRequest": {
      "description": "The request message containing the user's name.",
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        }
      }
    }
  }
}`))
}
