// Code generated by go-swagger; DO NOT EDIT.

package greeter

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "mygo/grpc/models"
)

// SayHelloOKCode is the HTTP code returned for type SayHelloOK
const SayHelloOKCode int = 200

/*SayHelloOK say hello o k

swagger:response sayHelloOK
*/
type SayHelloOK struct {

	/*
	  In: Body
	*/
	Payload *models.ProtoHelloReply `json:"body,omitempty"`
}

// NewSayHelloOK creates SayHelloOK with default headers values
func NewSayHelloOK() *SayHelloOK {

	return &SayHelloOK{}
}

// WithPayload adds the payload to the say hello o k response
func (o *SayHelloOK) WithPayload(payload *models.ProtoHelloReply) *SayHelloOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the say hello o k response
func (o *SayHelloOK) SetPayload(payload *models.ProtoHelloReply) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SayHelloOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
